spring:
  r2dbc:
   url: r2dbc:h2:mem:///testdb
   username: sa
   password:
     driver: h2
  h2:
    console:
      enabled: true
  web-flux:
    base-path: /api/v1/
management:
  endpoints:
    web:
      base-path: actuator

client:
  users: http://localhost:8080/api/v1/

server:
  port: 8081